<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
    </head>
    <body>
        <?php
       /* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */ 
        /* (int, int, int) -> list

        Returns a list of Fibonacci sequence of numbers that are less than or equal to the range. Num1 and num2 initiate the Fibonacci sequence.

     */

function fib_list($range, $num1, $num2)
{
$position = 0;
$sum = 0;
$list = [$num1, $num2];

    while ($sum < $range){
        $sum = $list[$position] + $list[$position+1];
        if ($sum <= $range){
            array_push($list, $sum);
            $position = $position + 1;
        }
    }

    print_r($list);
}

fib_list(10, 1, 2); 

        
        ?>
    </body>
</html>
